# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz_Robot_F.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1290, 564)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(self.frame)
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_superior.setStyleSheet("\n"
"QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton{\n"
"background-color: #000000ff;\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(53, 53, 79);\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(30, 30, 50); /* Cambia el color de fondo cuando se presiona */\n"
"    border: 1px solid rgb(200, 200, 200); /* Cambia el color del borde cuando se presiona */\n"
"}\n"
"\n"
"\n"
"")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_superior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Robot_Scara/imagenes/AREA.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(30, 40))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.frame_superior)
        self.label.setStyleSheet("font: 97 15pt \"Arial Black\";\n"
"color: rgb(0, 230, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(349, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_minimizar = QtWidgets.QPushButton(self.frame_superior)
        self.btn_minimizar.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_minimizar.setBaseSize(QtCore.QSize(40, 40))
        self.btn_minimizar.setStyleSheet("")
        self.btn_minimizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imagenes/signo-menos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimizar.setIcon(icon1)
        self.btn_minimizar.setIconSize(QtCore.QSize(30, 30))
        self.btn_minimizar.setObjectName("btn_minimizar")
        self.horizontalLayout_2.addWidget(self.btn_minimizar)
        self.btn_restaurar = QtWidgets.QPushButton(self.frame_superior)
        self.btn_restaurar.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_restaurar.setStyleSheet("")
        self.btn_restaurar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imagenes/minimizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_restaurar.setIcon(icon2)
        self.btn_restaurar.setIconSize(QtCore.QSize(30, 30))
        self.btn_restaurar.setObjectName("btn_restaurar")
        self.horizontalLayout_2.addWidget(self.btn_restaurar)
        self.btn_maximizar = QtWidgets.QPushButton(self.frame_superior)
        self.btn_maximizar.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_maximizar.setStyleSheet("")
        self.btn_maximizar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("imagenes/maximizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_maximizar.setIcon(icon3)
        self.btn_maximizar.setIconSize(QtCore.QSize(30, 30))
        self.btn_maximizar.setObjectName("btn_maximizar")
        self.horizontalLayout_2.addWidget(self.btn_maximizar)
        self.btn_cerrar = QtWidgets.QPushButton(self.frame_superior)
        self.btn_cerrar.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_cerrar.setStyleSheet("")
        self.btn_cerrar.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("imagenes/cerrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cerrar.setIcon(icon4)
        self.btn_cerrar.setIconSize(QtCore.QSize(30, 30))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.horizontalLayout_2.addWidget(self.btn_cerrar)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolBox = QtWidgets.QToolBox(self.frame_2)
        self.toolBox.setStyleSheet("\n"
"QToolBox::tab{\n"
"    background-color: rgb(255, 255, 255); \n"
"    border-radius: Spic;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 75 12pt \"MS Shell Dig 2\";\n"
"}\n"
"\n"
"QToolBox::tab:selected {\n"
"    background-color: rgb(0, 230, 255);\n"
"    font: 75 16pt \"MS Shell Dig 2\";\n"
"    color: rgb(0, 0, 0);    \n"
"}\n"
"")
        self.toolBox.setObjectName("toolBox")
        self.Nombre_2 = QtWidgets.QWidget()
        self.Nombre_2.setGeometry(QtCore.QRect(0, 0, 455, 406))
        self.Nombre_2.setObjectName("Nombre_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.Nombre_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem1 = QtWidgets.QSpacerItem(20, 54, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem2 = QtWidgets.QSpacerItem(21, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.label_9 = QtWidgets.QLabel(self.Nombre_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: transparent;\n"
"qproperty-alignment: \'AlignCenter\';")
        self.label_9.setWordWrap(False)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        spacerItem3 = QtWidgets.QSpacerItem(21, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.txt_nombre = QtWidgets.QPlainTextEdit(self.Nombre_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_nombre.sizePolicy().hasHeightForWidth())
        self.txt_nombre.setSizePolicy(sizePolicy)
        self.txt_nombre.setMaximumSize(QtCore.QSize(200, 40))
        self.txt_nombre.setStyleSheet("QPlainTextEdit{\n"
"border:2px solid #00E6FF;\n"
"border-radius:8px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0); \n"
"font: 75 15pt \"Times New Roman\";\n"
"qproperty-alignment: \'AlignCenter\';\n"
"align-content: \'center\';\n"
"\n"
"}")
        self.txt_nombre.setCenterOnScroll(False)
        self.txt_nombre.setObjectName("txt_nombre")
        self.horizontalLayout_8.addWidget(self.txt_nombre, 0, QtCore.Qt.AlignHCenter)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.aceptar_Nombre = QtWidgets.QPushButton(self.Nombre_2)
        self.aceptar_Nombre.setStyleSheet("\n"
"QPushButton{\n"
"    font: 87 15pt \"Arial Black\";\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(0, 230, 255); \n"
"    border-radius: 5px; \n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(53, 53, 79);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(30, 30, 50); /* Cambia el color de fondo cuando se presiona */\n"
"    border: 1px solid rgb(200, 200, 200); /* Cambia el color del borde cuando se presiona */\n"
"}")
        self.aceptar_Nombre.setObjectName("aceptar_Nombre")
        self.horizontalLayout_7.addWidget(self.aceptar_Nombre)
        spacerItem7 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        spacerItem8 = QtWidgets.QSpacerItem(20, 54, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem8)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../Robot_Scara/imagenes/firma-digital.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.Nombre_2, icon5, "")
        self.Camara = QtWidgets.QWidget()
        self.Camara.setGeometry(QtCore.QRect(0, 0, 455, 406))
        self.Camara.setObjectName("Camara")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.Camara)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_7 = QtWidgets.QFrame(self.Camara)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setStyleSheet("QLabel {\n"
"    font-family: \"Arial Black\";\n"
"    font-size: 12pt; /* Ajusta el tamaño de la fuente según lo necesites */\n"
"    color: white; /* Ajusta el color del texto si es necesario */\n"
"    background-color: transparent; /* Asegura que el fondo sea transparente */\n"
"    word-wrap: break-word; /* Permite que el texto se ajuste en múltiples líneas */\n"
"    white-space: normal; /* Permite que el texto se ajuste en múltiples líneas */\n"
"    padding: 5px; /* Añade un poco de espacio alrededor del texto */\n"
"    border: none; /* Elimina el borde si no es necesario */\n"
"    min-width: 200px; /* Ajusta el ancho mínimo si es necesario */\n"
"}")
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.verticalLayout_11.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.Camara)
        self.frame_8.setStyleSheet("QFrame{\n"
"background-color: rgb(0,0, 0);\n"
"}\n"
"QPushButton{\n"
"    font: 87 15pt \"Arial Black\";\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(0, 230, 255); \n"
"    border-radius: 5px; \n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(53, 53, 79);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(30, 30, 50); /* Cambia el color de fondo cuando se presiona */\n"
"    border: 1px solid rgb(200, 200, 200); /* Cambia el color del borde cuando se presiona */\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_13 = QtWidgets.QFrame(self.frame_9)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Iniciar_Camara = QtWidgets.QPushButton(self.frame_13)
        self.Iniciar_Camara.setObjectName("Iniciar_Camara")
        self.verticalLayout_7.addWidget(self.Iniciar_Camara)
        spacerItem9 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem9)
        self.Detener_Camara = QtWidgets.QPushButton(self.frame_13)
        self.Detener_Camara.setObjectName("Detener_Camara")
        self.verticalLayout_7.addWidget(self.Detener_Camara)
        spacerItem10 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem10)
        self.horizontalLayout_10.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_9)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Tomar_Foto = QtWidgets.QPushButton(self.frame_14)
        self.Tomar_Foto.setObjectName("Tomar_Foto")
        self.verticalLayout_8.addWidget(self.Tomar_Foto)
        spacerItem11 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem11)
        self.Contornos = QtWidgets.QPushButton(self.frame_14)
        self.Contornos.setObjectName("Contornos")
        self.verticalLayout_8.addWidget(self.Contornos)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem12)
        self.horizontalLayout_10.addWidget(self.frame_14)
        self.verticalLayout_6.addWidget(self.frame_9)
        self.frame_12 = QtWidgets.QFrame(self.frame_8)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_12.setSizeIncrement(QtCore.QSize(0, 10))
        self.frame_12.setStyleSheet("")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Realizar_Dibujo = QtWidgets.QPushButton(self.frame_12)
        self.Realizar_Dibujo.setMinimumSize(QtCore.QSize(0, 30))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("imagenes/brazo-robotico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Realizar_Dibujo.setIcon(icon6)
        self.Realizar_Dibujo.setObjectName("Realizar_Dibujo")
        self.verticalLayout_9.addWidget(self.Realizar_Dibujo)
        self.verticalLayout_6.addWidget(self.frame_12)
        self.verticalLayout_6.setStretch(0, 2)
        self.verticalLayout_6.setStretch(1, 1)
        self.verticalLayout_11.addWidget(self.frame_8)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("imagenes/ima.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.Camara, icon7, "")
        self.verticalLayout_3.addWidget(self.toolBox)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setStyleSheet("QLabel {\n"
"    font-family: \"Arial Black\";\n"
"    font-size: 15pt; /* Ajusta el tamaño de la fuente según lo necesites */\n"
"    color: white; /* Ajusta el color del texto si es necesario */\n"
"    background-color: transparent; /* Asegura que el fondo sea transparente */\n"
"    word-wrap: break-word; /* Permite que el texto se ajuste en múltiples líneas */\n"
"    white-space: normal; /* Permite que el texto se ajuste en múltiples líneas */\n"
"    padding: 5px; /* Añade un poco de espacio alrededor del texto */\n"
"    border: none; /* Elimina el borde si no es necesario */\n"
"    min-width: 200px; /* Ajusta el ancho mínimo si es necesario */    \n"
"qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_6)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_nombre = QtWidgets.QWidget()
        self.page_nombre.setObjectName("page_nombre")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_nombre)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_10 = QtWidgets.QFrame(self.page_nombre)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_grafica = QtWidgets.QVBoxLayout()
        self.verticalLayout_grafica.setObjectName("verticalLayout_grafica")
        self.horizontalLayout_4.addLayout(self.verticalLayout_grafica)
        self.horizontalLayout_3.addWidget(self.frame_10)
        self.stackedWidget.addWidget(self.page_nombre)
        self.page_camara = QtWidgets.QWidget()
        self.page_camara.setObjectName("page_camara")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_camara)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_11 = QtWidgets.QFrame(self.page_camara)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.layaout_grafica_camara = QtWidgets.QVBoxLayout()
        self.layaout_grafica_camara.setSpacing(0)
        self.layaout_grafica_camara.setObjectName("layaout_grafica_camara")
        self.horizontalLayout_6.addLayout(self.layaout_grafica_camara)
        self.layout_camara = QtWidgets.QHBoxLayout()
        self.layout_camara.setSpacing(0)
        self.layout_camara.setObjectName("layout_camara")
        self.horizontalLayout_6.addLayout(self.layout_camara)
        self.horizontalLayout_5.addWidget(self.frame_11)
        self.stackedWidget.addWidget(self.page_camara)
        self.horizontalLayout_12.addWidget(self.stackedWidget)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.frame_4)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 5)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ROBOT SCARA: Panel de Operaciones"))
        self.label_9.setText(_translate("MainWindow", "Ingrese un nombre (máx. 9 letras):"))
        self.aceptar_Nombre.setText(_translate("MainWindow", "ACEPTAR"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Nombre_2), _translate("MainWindow", "Nombre"))
        self.label_10.setText(_translate("MainWindow", "Tomé una foto para que el robot Scara dibuje los contornos"))
        self.Iniciar_Camara.setText(_translate("MainWindow", "Iniciar Camara"))
        self.Detener_Camara.setText(_translate("MainWindow", "Detener Camara"))
        self.Tomar_Foto.setText(_translate("MainWindow", "Tomar Foto"))
        self.Contornos.setText(_translate("MainWindow", "Contornos"))
        self.Realizar_Dibujo.setText(_translate("MainWindow", "Relizar Dibujo"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Camara), _translate("MainWindow", "Camara"))
        self.label_2.setText(_translate("MainWindow", "Panel de visualización del Robot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
